# Generated by Django 3.0.2 on 2020-01-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
