# Generated by Django 3.0.2 on 2020-01-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_userdata_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='transaction_category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='transaction_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transaction_date',
            field=models.CharField(max_length=50),
        ),
    ]
