# Generated by Django 3.0.2 on 2020-01-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200107_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
