# Generated by Django 3.0.2 on 2020-01-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_usersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersummary',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
