# Generated by Django 3.0.2 on 2020-01-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_usersummary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersummary',
            name='breakdown',
            field=models.TextField(null=True),
        ),
    ]
